@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}
@jokeId = 6599850700b3c8369f05b21a

### Create
POST {{host}}/api/jokes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "question": "hello?",
  "answer": "hello ahah!",
  "category": "fun"
  }

### Delete
DELETE {{host}}/api/jokes/{{jokeId}} HTTP/1.1
Accept: application/json

### Read All
GET {{host}}/api/jokes HTTP/1.1
Accept: application/json

### Read by Id
GET {{host}}/api/jokes/{{jokeId}} HTTP/1.1
Accept: application/json